<a href="https://colab.research.google.com/github/file00/Algorithms/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch


## Tensor
        Numpy Library의 ndarray Class와 유사한 구조로 Array or Matrix와 유사한 자료 구조(자료형)
        PyTorch에서는 Model의 Input/Output뿐만 아니라 Model의 매개변수를 Encode하고 GPU를 활용해 연산 가속화 가능
        torch.tensor() or torch.Tensor()로 생성할 수 있음  
            - torch.tensor()는 Input된 Data를 Copy 해 Tensor로 변환하는 함수임
            -> Data를 Copy 하므로 Value가 무조건 있어야 하며, Input 된 Data의 Type에 맞는 가장 적합한 Tensor 자료형으로 변환함.
            (비어있는 구조로 생성되지 않고 자동으로 자료형을 할당하기 때문에 의도치 않은 자료형으로 변경될 수 있으니, 사용에 주의 필요로 함)
            - torch.Tensor(): Tensor Instance를 생성하는 Tensor의 기본형 Class
            -> Instance를 생성하기 때문에 Value를 Input 하지 않은 경우 빈 Tensor를 생성함.
            (가급적 자료형이 명확하게 표현되는 Class 형태의 torch.Tensor()를 사용하는 것을 권장함)


In [ ]:
import torch

print(torch.tensor([1,2,3]))
print(torch.Tensor([[1,2,3],[4,5,6]]))
print(torch.LongTensor([1,2,3]))
print(torch.FloatTensor([1,2,3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


### Attribute of Tensor

In [ ]:
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.1905, 0.1473]])
torch.Size([1, 2])
torch.float32
cpu


### Dimension Transformation



In [ ]:
tensor = torch.rand(1,2)
print(tensor)
print(tensor.shape)

tensor = tensor.reshape(2,1)
print(tensor)
print(tensor.shape)

tensor([[0.4679, 0.0895]])
torch.Size([1, 2])
tensor([[0.4679],
        [0.0895]])
torch.Size([2, 1])
